// frontend/src/components/sidebar/SidebarItem.tsx
import React, { FunctionComponent } from 'react';
import SidebarContext from './SidebarContext';

type SidebarItemProps = {
  itemId: number;
  setActiveItem: (itemId: number) => void;
};

const SidebarItem: FunctionComponent<SidebarItemProps> = (
  props
): JSX.Element => {
  const toggle = (): void => {
    props.setActiveItem(props.itemId);
  };

  return (
    <SidebarContext.Consumer>
      {({ activeItem }) => {
        return (
          <div
            className={
              `flex items-center pl-12 space-x-6 cursor-pointer ` +
              `${
                activeItem === props.itemId
                  ? 'text-pink-600 border-pink-600 border-r-2 font-semibold'
                  : 'text-gray-600'
              }`
            }
            onClick={toggle}>
            {props.children}
          </div>
        );
      }}
    </SidebarContext.Consumer>
  );
};

export default SidebarItem;

// frontend/src/components/sidebar/SidebarItem.vue
<template>
  <div
    class="flex items-center pl-12 space-x-6 cursor-pointer"
    :class="{
      'text-pink-600 border-pink-600 border-r-2 font-semibold': isActive,
      'text-gray-600': !isActive,
    }"
    @click="toggle"
  >
    <slot />
  </div>
</template>

<script lang="ts">
import {
  defineComponent, computed, inject, ref,
} from 'vue';
import { SidebarSharedState } from '../../models/SidebarSharedState';

export default defineComponent({
  props: {
    itemId: {
      type: Number,
      required: true,
    },
  },
  setup(props) {
    const sharedState = ref(inject('sharedState') as SidebarSharedState);
    const isActive = computed(() => sharedState.value.activeItem === props.itemId);

    const toggle = () => {
      sharedState.value.activeItem = props.itemId;
    };

    return {
      isActive,
      toggle,
    };
  },
});
</script>
